# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Peter
tagline:          'A Jekyll theme'
description:      "A software engineer's ramblings on languages, linux, and life."
url:              http://peternguyen.io
baseurl:          /

author:
  name:           'Peter Nguyen'
  url:            https://github.com/peterlnguyen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/peterlnguyen

linkedin:         https://linkedin.com/in/peterlongnguyen
